[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = False
warn_redundant_casts = True
warn_unused_configs = True
ignore_missing_imports = True
show_error_codes = True

[mypy-rlm.environments.*]
ignore_errors = True

[mypy-rlm.clients.*]
ignore_errors = True

[mypy-rlm.logger.*]
ignore_errors = True

[mypy-rlm.agents.*]
ignore_errors = True

[mypy-rlm.console.*]
ignore_errors = True

[mypy-rlm.redux.middleware.*]
ignore_errors = True

[mypy-rlm.utils.key_encryption]
ignore_errors = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-rlm.routing.*]
ignore_errors = True

[mypy-rlm.core.rlm]
ignore_errors = True
