"""
Redux slices for state management.

This package contains individual Redux slices for different aspects
of RLM system state.
"""

from rlm.redux.slices.agent_loop_slice import (
    AgentLoopStatus,
    LLMCallType,
    LLMCallRecord,
    REPLExecutionRecord,
    IterationRecord,
    SpawningEvent,
    ChainThoughtStep,
    AgentLoopState,
    AgentLoopSlice,
    AgentLoopActions,
    agent_loop_reducer,
)

from rlm.redux.slices.verification_slice import (
    VerificationStatus,
    Layer1State,
    TheoremVerification,
    VerificationState,
    VerificationActions,
    verification_reducer,
)

from rlm.redux.slices.routing_slice import (
    RoutingDecisionType,
    RoutingDecision,
    BackendMetrics,
    RoutingState,
    RoutingActions,
    routing_reducer,
)

from rlm.redux.slices.tasks_slice import (
    TaskStatus,
    TaskPriority,
    TaskConstraints,
    TaskRouting,
    TaskClassification,
    TaskEntity,
    TaskSubmissionDraft,
    TasksState,
    TasksActions,
    tasks_reducer,
)

from rlm.redux.slices.permissions_slice import (
    PermissionAction,
    PermissionType,
    PermissionRequest,
    PermissionDefaults,
    PermissionRecord,
    PermissionsState,
    PermissionsActions,
    permissions_reducer,
)

from rlm.redux.slices.tools_slice import (
    ToolStatus,
    ToolDefinition,
    ToolDefaults,
    ToolsState,
    ToolsActions,
    tools_reducer,
)

from rlm.redux.slices.improvements_slice import (
    ImprovementStatus,
    ImprovementEntity,
    ImprovementDefaults,
    ImprovementsState,
    ImprovementsActions,
    improvements_reducer,
)

from rlm.redux.slices.agents_slice import (
    AgentStatus,
    InterventionActionType,
    AgentEntity,
    InterventionRecord,
    AgentsState,
    AgentsActions,
    agents_reducer,
)

from rlm.redux.slices.messages_slice import (
    MessagePriority,
    MessageEntity,
    MessageThread,
    MessageRetention,
    MessagesState,
    MessagesActions,
    messages_reducer,
)

from rlm.redux.slices.system_slice import (
    RealtimeMode,
    ResourceLimits,
    SecuritySettings,
    PerformanceSettings,
    RealtimeSettings,
    RetentionSettings,
    SystemConfiguration,
    SystemState,
    SystemActions,
    system_reducer,
)

from rlm.redux.slices.ui_slice import (
    PanelId,
    Notification,
    UIState,
    UIActions,
    ui_reducer,
)

from rlm.redux.slices.loop_slice import (
    LoopStatus,
    CandidateStatus,
    InterruptPriority,
    LoopMetrics,
    ReleaseCandidate,
    CertifiedCandidate,
    Interrupt,
    LoopState,
    LoopActions,
    loop_reducer,
)

from rlm.redux.slices.domain_slice import (
    DomainType,
    ClassificationConfidence,
    DomainConfig,
    Layer1Context,
    DomainClassification,
    DomainMismatchRecord,
    DomainState,
    DomainActions,
    domain_reducer,
)

from rlm.redux.slices.synthesis_slice import (
    SynthesisStatus,
    DomainCollisionStatus,
    CrossDomainInvariant,
    DomainMapping,
    UnifiedDomainStructure,
    Proof,
    SynthesisTask,
    SynthesisState,
    SynthesisActions,
    synthesis_reducer,
)

from rlm.redux.slices.fuzzing_slice import (
    FuzzingStatus,
    SandboxEnvironment,
    SandboxResponse,
    InputSpace,
    MembershipQuery,
    FSMState,
    FSMTransition,
    DiscoveredFSM,
    FuzzingTask,
    SandboxState,
    FuzzingState,
    FuzzingActions,
    fuzzing_reducer,
)

from rlm.redux.slices.skunkworks_slice import (
    SkunkworksStatus,
    HypothesisConfidence,
    HypothesisStatus,
    Hypothesis,
    ExplorationLog,
    UserCollaborationRequest,
    SkunkworksSession,
    SkunkworksState,
    SkunkworksActions,
    skunkworks_reducer,
)

from rlm.redux.slices.ontology_slice import (
    OntologyStatus,
    InhabitationProofStatus,
    StructureInvariant,
    StateTransitionFunction,
    OntologyStructure,
    GenesisState,
    InvariantProof,
    OntologyTask,
    OntologyState,
    OntologyActions,
    ontology_reducer,
)

from rlm.redux.slices.edge_slice import (
    EdgeDomainType,
    SandboxSecurityLevel,
    OverrideSource,
    UserAxiomOverride,
    Layer1_5Override,
    HardwareProtocolState,
    SandboxConfig,
    EdgeDomainState,
    EdgeActions,
    edge_reducer,
)

__all__ = [
    "AgentLoopStatus",
    "LLMCallType",
    "LLMCallRecord",
    "REPLExecutionRecord",
    "IterationRecord",
    "SpawningEvent",
    "ChainThoughtStep",
    "AgentLoopState",
    "AgentLoopSlice",
    "AgentLoopActions",
    "agent_loop_reducer",
    "VerificationStatus",
    "Layer1State",
    "TheoremVerification",
    "VerificationState",
    "VerificationActions",
    "verification_reducer",
    "RoutingDecisionType",
    "RoutingDecision",
    "BackendMetrics",
    "RoutingState",
    "RoutingActions",
    "routing_reducer",
    "TaskStatus",
    "TaskPriority",
    "TaskConstraints",
    "TaskRouting",
    "TaskClassification",
    "TaskEntity",
    "TaskSubmissionDraft",
    "TasksState",
    "TasksActions",
    "tasks_reducer",
    "PermissionAction",
    "PermissionType",
    "PermissionRequest",
    "PermissionDefaults",
    "PermissionRecord",
    "PermissionsState",
    "PermissionsActions",
    "permissions_reducer",
    "ToolStatus",
    "ToolDefinition",
    "ToolDefaults",
    "ToolsState",
    "ToolsActions",
    "tools_reducer",
    "ImprovementStatus",
    "ImprovementEntity",
    "ImprovementDefaults",
    "ImprovementsState",
    "ImprovementsActions",
    "improvements_reducer",
    "AgentStatus",
    "InterventionActionType",
    "AgentEntity",
    "InterventionRecord",
    "AgentsState",
    "AgentsActions",
    "agents_reducer",
    "MessagePriority",
    "MessageEntity",
    "MessageThread",
    "MessageRetention",
    "MessagesState",
    "MessagesActions",
    "messages_reducer",
    "RealtimeMode",
    "ResourceLimits",
    "SecuritySettings",
    "PerformanceSettings",
    "RealtimeSettings",
    "RetentionSettings",
    "SystemConfiguration",
    "SystemState",
    "SystemActions",
    "system_reducer",
    "PanelId",
    "Notification",
    "UIState",
    "UIActions",
    "ui_reducer",
    "LoopStatus",
    "CandidateStatus",
    "InterruptPriority",
    "LoopMetrics",
    "ReleaseCandidate",
    "CertifiedCandidate",
    "Interrupt",
    "LoopState",
    "LoopActions",
    "loop_reducer",
    "DomainType",
    "ClassificationConfidence",
    "DomainConfig",
    "Layer1Context",
    "DomainClassification",
    "DomainMismatchRecord",
    "DomainState",
    "DomainActions",
    "domain_reducer",
    "SynthesisStatus",
    "DomainCollisionStatus",
    "CrossDomainInvariant",
    "DomainMapping",
    "UnifiedDomainStructure",
    "Proof",
    "SynthesisTask",
    "SynthesisState",
    "SynthesisActions",
    "synthesis_reducer",
    "FuzzingStatus",
    "SandboxEnvironment",
    "SandboxResponse",
    "InputSpace",
    "MembershipQuery",
    "FSMState",
    "FSMTransition",
    "DiscoveredFSM",
    "FuzzingTask",
    "SandboxState",
    "FuzzingState",
    "FuzzingActions",
    "fuzzing_reducer",
    "SkunkworksStatus",
    "HypothesisConfidence",
    "HypothesisStatus",
    "Hypothesis",
    "ExplorationLog",
    "UserCollaborationRequest",
    "SkunkworksSession",
    "SkunkworksState",
    "SkunkworksActions",
    "skunkworks_reducer",
    "OntologyStatus",
    "InhabitationProofStatus",
    "StructureInvariant",
    "StateTransitionFunction",
    "OntologyStructure",
    "GenesisState",
    "InvariantProof",
    "OntologyTask",
    "OntologyState",
    "OntologyActions",
    "ontology_reducer",
    "EdgeDomainType",
    "SandboxSecurityLevel",
    "OverrideSource",
    "UserAxiomOverride",
    "Layer1_5Override",
    "HardwareProtocolState",
    "SandboxConfig",
    "EdgeDomainState",
    "EdgeActions",
    "edge_reducer",
]
