"""
Empirical Fuzzing Loop (Automata Learning).

This module implements the Empirical Fuzzing Loop for black-box protocol discovery
using Angluin's L* algorithm. It provides structured automata learning for
discovering finite state machines from undocumented APIs, hardware, or binaries.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Callable, Any, Tuple
from enum import Enum
import random
import time
import threading


class SandboxResponse(Enum):
    """Response types from sandbox."""

    VALID_TRANSITION = "valid_transition"
    REJECTED = "rejected"
    TIMEOUT = "timeout"
    CRASH = "crash"
    UNKNOWN = "unknown"


class FuzzingStatus(Enum):
    """Status of fuzzing task."""

    IDLE = "idle"
    INITIALIZING = "initializing"
    LEARNING = "learning"
    HYPOTHESIZING = "hypothesizing"
    EQUIVALENCE_TESTING = "equivalence_testing"
    REFINING = "refining"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class InputSymbol:
    """An input symbol for the automata."""

    name: str
    representation: str
    encoding: bytes = field(default_factory=lambda: b"")


@dataclass
class State:
    """A state in the discovered automaton."""

    id: int
    name: str
    is_accepting: bool = False
    is_initial: bool = False


@dataclass
class Transition:
    """A transition in the automaton."""

    from_state: int
    to_state: int
    input_symbol: str
    output_symbol: Optional[str] = None


@dataclass
class Automaton:
    """
    A learned finite state machine.

    Attributes:
        states: Set of states
        alphabet: Set of input symbols
        transitions: Set of transitions
        initial_state: ID of initial state
        accepting_states: Set of accepting state IDs
    """

    states: Set[int] = field(default_factory=set)
    alphabet: Set[str] = field(default_factory=set)
    transitions: Set[Tuple[int, str, int]] = field(default_factory=set)
    initial_state: int = 0
    accepting_states: Set[int] = field(default_factory=set)

    def get_transition(self, state: int, symbol: str) -> Optional[int]:
        """Get target state for a transition."""
        for s, sym, t in self.transitions:
            if s == state and sym == symbol:
                return t
        return None

    def add_transition(self, from_state: int, symbol: str, to_state: int) -> None:
        """Add a transition."""
        self.states.add(from_state)
        self.states.add(to_state)
        self.alphabet.add(symbol)
        self.transitions.add((from_state, symbol, to_state))

    def to_haskell(self) -> str:
        """Generate Haskell ADT representation."""
        if not self.states:
            return "-- Empty automaton"

        # Generate state ADT
        state_names = [f"S{s}" for s in sorted(self.states)]
        lines = ["-- Discovered FSM", "-- Auto-generated by Empirical Fuzzing Loop", ""]
        lines.append("data AutomatonState =")
        for i, name in enumerate(state_names):
            if i < len(state_names) - 1:
                lines.append(f"    {name} |")
            else:
                lines.append(f"    {name}")
        lines.append("    deriving (Show, Eq)")
        lines.append("")

        # Generate transition function
        lines.append("transition :: AutomatonState -> InputSymbol -> AutomatonState")
        lines.append("transition state input = case (state, input) of")

        for s, sym, t in sorted(self.transitions):
            s_name = f"S{s}"
            t_name = f"S{t}"
            lines.append(f"    ({s_name}, {sym}) -> {t_name}")

        return "\n".join(lines)


@dataclass
class MembershipQuery:
    """A membership query to the teacher (sandbox)."""

    id: str
    input_sequence: List[str]
    response: SandboxResponse
    new_state_discovered: bool = False
    timestamp: float = field(default_factory=time.time)


@dataclass
class EquivalenceQuery:
    """An equivalence query to verify hypothesis."""

    id: str
    counterexample: Optional[List[str]] = None
    verified: bool = False
    tested_count: int = 0


@dataclass
class FuzzingHypothesis:
    """A hypothesis automaton from the learner."""

    automaton: Automaton
    created_at: float = field(default_factory=time.time)
    membership_queries: int = 0
    equivalence_tests: int = 0


class TeacherInterface:
    """
    Interface to the sandbox (teacher) for automata learning.

    This simulates the black-box system being learned.
    In production, this would wrap actual sandbox communication.
    """

    def __init__(
        self,
        sandbox_callable: Callable[[List[str]], SandboxResponse],
        timeout_seconds: int = 300,
    ):
        """
        Initialize the teacher interface.

        Args:
            sandbox_callable: Function that takes input sequence, returns response
            timeout_seconds: Maximum time for a query
        """
        self._sandbox = sandbox_callable
        self._timeout = timeout_seconds
        self._query_count = 0

    def membership_query(self, input_sequence: List[str]) -> SandboxResponse:
        """
        Execute a membership query.

        Args:
            input_sequence: Sequence of inputs to test

        Returns:
            Response from the sandbox
        """
        self._query_count += 1
        return self._sandbox(input_sequence)

    def get_query_count(self) -> int:
        """Get number of queries executed."""
        return self._query_count


class LStarLearner:
    """
    Implementation of Angluin's L* algorithm for automata learning.

    This algorithm learns a DFA (Deterministic Finite Automaton) through:
    1. Membership queries to determine transitions
    2. Equivalence queries to verify the hypothesis
    """

    def __init__(
        self,
        teacher: TeacherInterface,
        alphabet: Set[str],
    ):
        """
        Initialize the L* learner.

        Args:
            teacher: Teacher interface for queries
            alphabet: Set of input symbols
        """
        self._teacher = teacher
        self._alphabet = alphabet
        self._S: List[List[str]] = []  # Set of access sequences
        self._E: List[str] = []  # Set of distinguish sequences
        self._T: Dict[Tuple[List[str], str], bool] = {}  # Observation table
        self._hypothesis: Optional[Automaton] = None
        self._closed = False

    def learn(self, max_queries: int = 10000) -> Automaton:
        """
        Run the L* algorithm to learn the automaton.

        Args:
            max_queries: Maximum number of membership queries

        Returns:
            The learned automaton
        """
        # Initialize with empty sequence
        self._S = [[]]
        self._E = [""]
        self._initialize_table()

        query_count = 0

        while query_count < max_queries:
            # Make table closed and consistent
            self._make_closed()
            self._make_consistent()

            # Build hypothesis
            self._build_hypothesis()

            # Check equivalence
            eq_result = self._teacher.membership_query(["__EQUIVALENCE_CHECK__"])

            # In a real implementation, we'd do actual equivalence testing
            # For now, we assume the hypothesis is complete when table is stable

            if self._hypothesis and self._is_hypothesis_complete():
                break

        return self._hypothesis or Automaton()

    def _initialize_table(self) -> None:
        """Initialize the observation table."""
        # Query for all (s, e) pairs where s in S, e in E
        for s in self._S:
            for e in self._E:
                key = (tuple(s), e)
                if key not in self._T:
                    result = self._teacher.membership_query(s + [e] if e else s)
                    self._T[key] = result == SandboxResponse.VALID_TRANSITION

    def _make_closed(self) -> None:
        """Make the observation table closed."""
        for s in self._S:
            for a in self._alphabet:
                row = tuple(s + [a])
                # Check if row exists in S
                if list(row) not in self._S:
                    # Find matching row in S
                    match = self._find_matching_row(row)
                    if match is not None:
                        self._S.append(list(row))
                        self._initialize_new_rows(list(row))

    def _find_matching_row(self, target: Tuple) -> Optional[List[str]]:
        """Find a row in S that matches the target row."""
        target_values = [self._T.get((target, e), False) for e in self._E]
        for s in self._S:
            s_values = [self._T.get((tuple(s), e), False) for e in self._E]
            if s_values == target_values:
                return s
        return None

    def _make_consistent(self) -> None:
        """Make the observation table consistent."""
        for a in self._alphabet:
            for i, s1 in enumerate(self._S):
                for s2 in self._S[i + 1 :]:
                    # Check if rows are equivalent
                    if self._rows_equivalent(s1, s2):
                        # Check for inconsistency with transitions
                        for e in self._E:
                            key1 = (tuple(s1 + [a]), e)
                            key2 = (tuple(s2 + [a]), e)
                            val1 = self._T.get(key1, False)
                            val2 = self._T.get(key2, False)
                            if val1 != val2:
                                # Add distinguishing suffix
                                self._E.append(a + e)
                                self._initialize_new_rows(s1 + [a])
                                return

    def _rows_equivalent(self, s1: List[str], s2: List[str]) -> bool:
        """Check if two rows are equivalent in the observation table."""
        for e in self._E:
            key1 = (tuple(s1), e)
            key2 = (tuple(s2), e)
            val1 = self._T.get(key1, False)
            val2 = self._T.get(key2, False)
            if val1 != val2:
                return False
        return True

    def _initialize_new_rows(self, s: List[str]) -> None:
        """Initialize new rows for a sequence."""
        for e in self._E:
            key = (tuple(s), e)
            if key not in self._T:
                result = self._teacher.membership_query(s + [e] if e else s)
                self._T[key] = result == SandboxResponse.VALID_TRANSITION

    def _build_hypothesis(self) -> None:
        """Build a hypothesis automaton from the observation table."""
        self._hypothesis = Automaton()
        self._hypothesis.alphabet = self._alphabet.copy()

        # Map S rows to state IDs
        state_map: Dict[Tuple, int] = {}
        state_id = 0

        for s in self._S:
            row_key = tuple(self._T.get((tuple(s), e), False) for e in self._E)
            if row_key not in state_map:
                state_map[row_key] = state_id
                self._hypothesis.states.add(state_id)
                state_id += 1

        self._hypothesis.initial_state = 0
        if 0 in state_map.values():
            self._hypothesis.accepting_states.add(state_map[0])

        # Build transitions
        for s in self._S:
            for a in self._alphabet:
                s_prime = s + [a]
                # Find the row for s'
                row_key = tuple(
                    self._T.get((tuple(s_prime), e), False) for e in self._E
                )
                if row_key in state_map:
                    from_id = state_map.get(
                        tuple(self._T.get((tuple(s), e), False) for e in self._E), 0
                    )
                    to_id = state_map[row_key]
                    self._hypothesis.add_transition(from_id, a, to_id)

    def _is_hypothesis_complete(self) -> bool:
        """Check if the hypothesis is complete (table is closed and consistent)."""
        # Simplified check - in production would do full L* consistency checks
        return (
            self._hypothesis is not None
            and len(self._hypothesis.states) > 0
            and all(
                self._hypothesis.get_transition(s, a) is not None
                for s in self._hypothesis.states
                for a in self._alphabet
            )
        )


class FuzzingLoop:
    """
    The Empirical Fuzzing Loop for black-box protocol discovery.

    This implements:
    1. Input space definition
    2. Membership queries (L* learning)
    3. Hypothesis generation
    4. Equivalence fuzzing
    5. FSM refinement
    """

    def __init__(self, timeout_seconds: int = 300, max_queries: int = 10000):
        """
        Initialize the fuzzing loop.

        Args:
            timeout_seconds: Maximum time per fuzzing iteration
            max_queries: Maximum membership queries per learning run
        """
        self._timeout = timeout_seconds
        self._max_queries = max_queries
        self._status = FuzzingStatus.IDLE
        self._active_hypothesis: Optional[FuzzingHypothesis] = None
        self._membership_history: List[MembershipQuery] = []
        self._equivalence_history: List[EquivalenceQuery] = []
        self._discovered_automata: List[Automaton] = []
        self._lock = threading.Lock()

    def discover_automaton(
        self,
        input_alphabet: Set[str],
        teacher: TeacherInterface,
    ) -> Tuple[Automaton, List[MembershipQuery]]:
        """
        Discover an automaton using L* algorithm.

        Args:
            input_alphabet: Set of input symbols
            teacher: Teacher interface

        Returns:
            Tuple of (learned automaton, membership query history)
        """
        with self._lock:
            self._status = FuzzingStatus.LEARNING

        learner = LStarLearner(teacher, input_alphabet)
        automaton = learner.learn(max_queries=self._max_queries)

        with self._lock:
            self._status = FuzzingStatus.HYPOTHESIZING
            self._active_hypothesis = FuzzingHypothesis(automaton=automaton)
            self._discovered_automata.append(automaton)

        return automaton, self._membership_history.copy()

    def refine_hypothesis(
        self,
        counterexample: List[str],
        teacher: TeacherInterface,
    ) -> Automaton:
        """
        Refine hypothesis with a counterexample.

        Args:
            counterexample: Input sequence that disproves the hypothesis
            teacher: Teacher interface

        Returns:
            Refined automaton
        """
        with self._lock:
            self._status = FuzzingStatus.REFINING

        if not self._active_hypothesis:
            raise ValueError("No active hypothesis to refine")

        # In a full implementation, we'd add the counterexample to S
        # and re-run the L* algorithm
        # For now, we just update the status

        with self._lock:
            self._status = FuzzingStatus.LEARNING

        learner = LStarLearner(teacher, self._active_hypothesis.automaton.alphabet)
        automaton = learner.learn(max_queries=self._max_queries)

        with self._lock:
            self._active_hypothesis = FuzzingHypothesis(automaton=automaton)
            self._discovered_automata.append(automaton)

        return automaton

    def equivalence_fuzzing(
        self,
        hypothesis: Automaton,
        teacher: TeacherInterface,
        num_tests: int = 1000,
    ) -> Tuple[bool, Optional[List[str]]]:
        """
        Perform equivalence fuzzing on a hypothesis.

        Args:
            hypothesis: The hypothesis to test
            teacher: Teacher interface
            num_tests: Number of random sequences to test

        Returns:
            Tuple of (is_equivalent, counterexample if found)
        """
        for _ in range(num_tests):
            # Generate random sequence
            seq_len = random.randint(1, 5)
            sequence = random.choices(list(hypothesis.alphabet), k=seq_len)

            # Get hypothesis output
            state = hypothesis.initial_state
            for sym in sequence:
                next_state = hypothesis.get_transition(state, sym)
                if next_state is None:
                    break
                state = next_state

            # Check with teacher
            teacher_response = teacher.membership_query(sequence)

            # Determine if hypothesis is correct
            # (simplified - real implementation would track internal states)
            if teacher_response == SandboxResponse.CRASH:
                return False, sequence

        return True, None

    def generate_haskell_fsm(self, automaton: Automaton) -> str:
        """
        Generate Haskell FSM from discovered automaton.

        Args:
            automaton: The learned automaton

        Returns:
            Haskell code representation
        """
        return automaton.to_haskell()

    def get_status(self) -> FuzzingStatus:
        """Get current fuzzing status."""
        return self._status

    def get_active_hypothesis(self) -> Optional[Automaton]:
        """Get the active hypothesis automaton."""
        if self._active_hypothesis:
            return self._active_hypothesis.automaton
        return None

    def get_discovered_automata(self) -> List[Automaton]:
        """Get all discovered automata."""
        return self._discovered_automata.copy()

    def get_membership_history(self) -> List[MembershipQuery]:
        """Get membership query history."""
        return self._membership_history.copy()
